import type { ApiConfig } from '../api/types'
import { personaDb } from '../wechat/newFriendsPersona/idb'
import type { CharacterMemory, PulseMemoryPayload } from '../wechat/newFriendsPersona/types'
import { composeMemoryWithSourcePrefix } from '../wechat/memory/memorySourceBadges'

import {
  buildPulsePostMemoryPayload,
  pulsePostMemoryId,
} from './pulsePostMemoryContentBuilder'
import { extractPulsePostMemoryKeywords } from './pulsePostMemoryKeywordAi'
import type { PulseComment, PulsePersistedRoot, PulsePost } from './pulseTypes'
import { parsePulsePovId } from './pulseTypes'

const ARCHIVE_DEBOUNCE_MS = 4000

export type CharacterPulsePostArchiveJob = {
  post: PulsePost
  comments: PulseComment[]
  trendingTitle?: string
  apiConfig?: ApiConfig | null
  wechatAccountId?: string | null
  playerIdentityId?: string | null
}

type PendingArchive = {
  timer: number
  job: CharacterPulsePostArchiveJob
}

const pendingArchives = new Map<string, PendingArchive>()

function isArchivableCharacterPulsePost(post: PulsePost): boolean {
  const parsed = parsePulsePovId(post.authorPovId)
  return parsed?.kind === 'char' && Boolean(parsed.rawId.trim())
}

function resolvePublisherCharacterId(post: PulsePost): string | null {
  const parsed = parsePulsePovId(post.authorPovId)
  if (parsed?.kind !== 'char') return null
  const id = parsed.rawId.trim()
  return id || null
}

async function findPublisherPulseMemory(
  characterId: string,
  postId: string,
): Promise<CharacterMemory | null> {
  const list = await personaDb.listCharacterMemoriesForCharacter(characterId)
  const stableId = pulsePostMemoryId(postId)
  return (
    list.find(
      (m) =>
        m.id === stableId ||
        (m.memoryScope === 'pulse' && m.pulseSourcePostId === postId),
    ) ?? null
  )
}

async function flushCharacterPulsePostArchive(job: CharacterPulsePostArchiveJob): Promise<void> {
  const post = job.post
  if (!isArchivableCharacterPulsePost(post)) return
  const publisherCharacterId = resolvePublisherCharacterId(post)
  if (!publisherCharacterId) return

  const { payload, memoryContent } = buildPulsePostMemoryPayload({
    post,
    comments: job.comments,
    trendingTitle: job.trendingTitle,
  })

  const existing = await findPublisherPulseMemory(publisherCharacterId, post.id)
  const archivedAt = Date.now()
  const createdAt = existing?.createdAt ?? post.createdAt
  const memoryId = existing?.id ?? pulsePostMemoryId(post.id)
  const publishedAt =
    Number.isFinite(post.createdAt) && post.createdAt > 0 ? post.createdAt : createdAt

  const bodyUnchanged =
    existing?.pulsePayload?.originalText?.trim() === payload.originalText.trim()
  const prevImages = (existing?.pulsePayload?.imageDescriptions ?? []).join('\n')
  const nextImages = (payload.imageDescriptions ?? []).join('\n')
  const imagesUnchanged = prevImages === nextImages
  let keywords = existing?.memoryKeywords?.filter(Boolean) ?? []
  if (!bodyUnchanged || !imagesUnchanged || !keywords.length) {
    keywords = await extractPulsePostMemoryKeywords({
      apiConfig: job.apiConfig,
      postText: payload.originalText,
      location: payload.location,
      trendingTitle: job.trendingTitle,
      imageDescriptions: payload.imageDescriptions,
    })
  }

  const publisherContent = composeMemoryWithSourcePrefix({ hasPulseTag: true }, memoryContent.trim())

  const pulsePayload: PulseMemoryPayload = {
    ...payload,
    publishedAt,
  }

  const row: CharacterMemory = {
    id: memoryId,
    characterId: publisherCharacterId,
    content: publisherContent.slice(0, 4000),
    createdAt,
    updatedAt: archivedAt,
    isAutoGenerated: true,
    memoryScope: 'pulse',
    memoryTriggerMode: 'keyword',
    memoryKeywords: keywords.length ? keywords : ['微博'],
    pulseSourcePostId: post.id,
    pulsePayload,
    ...(job.wechatAccountId?.trim()
      ? { sourceWechatAccountId: job.wechatAccountId.trim() }
      : {}),
    ...(job.playerIdentityId?.trim() && job.playerIdentityId !== '__none__'
      ? { sourceSessionPlayerIdentityId: job.playerIdentityId.trim() }
      : {}),
  }

  await personaDb.upsertCharacterMemory(row)
}

/** 防抖写入：角色微博发帖 / 评论变更后刻录入长期记忆 */
export function scheduleCharacterPulsePostArchive(job: CharacterPulsePostArchiveJob): void {
  const postId = job.post.id.trim()
  if (!postId || !isArchivableCharacterPulsePost(job.post)) return

  const prev = pendingArchives.get(postId)
  if (prev) window.clearTimeout(prev.timer)

  const timer = window.setTimeout(() => {
    pendingArchives.delete(postId)
    void flushCharacterPulsePostArchive(job).catch(() => {
      // silent
    })
  }, ARCHIVE_DEBOUNCE_MS)

  pendingArchives.set(postId, { timer, job })
}

/** 从 Pulse 持久化树查找帖子与评论，并调度归档 */
export function schedulePulsePostMemoryFromRoot(params: {
  root: PulsePersistedRoot
  accountId: string
  postId: string
  apiConfig?: ApiConfig | null
  wechatAccountId?: string | null
  playerIdentityId?: string | null
}): void {
  const acc = params.root.byAccount[params.accountId]
  if (!acc) return
  const pid = params.postId.trim()
  if (!pid) return

  let post: PulsePost | undefined
  let comments: PulseComment[] = []
  let trendingTitle: string | undefined

  for (const world of Object.values(acc.worldByPov ?? {})) {
    const hit = world.posts.find((p) => p.id === pid)
    if (hit) {
      post = hit
      comments = world.commentsByPostId[pid] ?? []
      if (hit.trendingTopicId) {
        const topic = world.trending.find((t) => t.id === hit.trendingTopicId)
        trendingTitle = topic?.title
      }
      break
    }
  }

  if (!post) return

  scheduleCharacterPulsePostArchive({
    post,
    comments,
    trendingTitle,
    apiConfig: params.apiConfig,
    wechatAccountId: params.wechatAccountId,
    playerIdentityId: params.playerIdentityId,
  })
}

/** 将某角色当前世界下全部微博帖调度进长期记忆（用于主页打开时补刻录） */
export function scheduleAllCharacterPulsePostsMemoryFromRoot(params: {
  root: PulsePersistedRoot
  accountId: string
  authorPovId: string
  apiConfig?: ApiConfig | null
  wechatAccountId?: string | null
  playerIdentityId?: string | null
}): void {
  const author = params.authorPovId.trim()
  const parsed = parsePulsePovId(author)
  if (parsed?.kind !== 'char') return
  const acc = params.root.byAccount[params.accountId]
  if (!acc) return

  const seen = new Set<string>()
  for (const world of Object.values(acc.worldByPov ?? {})) {
    for (const post of world.posts) {
      if (post.authorPovId.trim() !== author) continue
      if (seen.has(post.id)) continue
      seen.add(post.id)
      schedulePulsePostMemoryFromRoot({
        ...params,
        postId: post.id,
      })
    }
  }
}

/** 取消尚未落盘的防抖归档，避免清帖后又被写回 */
export function cancelPendingPulsePostArchives(postIds: Iterable<string>): void {
  for (const raw of postIds) {
    const postId = raw.trim()
    if (!postId) continue
    const prev = pendingArchives.get(postId)
    if (!prev) continue
    window.clearTimeout(prev.timer)
    pendingArchives.delete(postId)
  }
}

/** 删除帖子对应的微博长期记忆（同步取消待写入任务） */
export async function removePulsePostMemories(
  postIds: string[],
  opts?: { characterId?: string },
): Promise<void> {
  const ids = [...new Set(postIds.map((x) => x.trim()).filter(Boolean))]
  if (!ids.length) return

  cancelPendingPulsePostArchives(ids)

  const idSet = new Set(ids)
  const stableMemoryIds = new Set(ids.map((id) => pulsePostMemoryId(id)))
  await Promise.all([...stableMemoryIds].map((mid) => personaDb.deleteCharacterMemory(mid)))

  const characterId = opts?.characterId?.trim()
  if (!characterId) return

  const list = await personaDb.listCharacterMemoriesForCharacter(characterId)
  const extraIds = list
    .filter((m) => {
      if (stableMemoryIds.has(m.id)) return false
      if (m.pulseSourcePostId && idSet.has(m.pulseSourcePostId)) return true
      if (m.memoryScope === 'pulse' && m.pulseSourcePostId && idSet.has(m.pulseSourcePostId)) return true
      return false
    })
    .map((m) => m.id)

  if (extraIds.length) {
    await Promise.all(extraIds.map((id) => personaDb.deleteCharacterMemory(id)))
  }
}

/**
 * 清除角色全部微博长期记忆（用于「清除历史动态」）。
 * 含 scope=pulse / pulseSourcePostId / [微博] 前缀条目。
 */
export async function removeAllPulseMemoriesForCharacter(characterId: string): Promise<void> {
  const cid = characterId.trim()
  if (!cid) return

  const list = await personaDb.listCharacterMemoriesForCharacter(cid)
  const pulseRows = list.filter(
    (m) =>
      m.memoryScope === 'pulse' ||
      Boolean(m.pulseSourcePostId?.trim()) ||
      m.id.startsWith('pulse-mem-') ||
      m.content.trimStart().startsWith('[微博]'),
  )
  if (!pulseRows.length) return

  cancelPendingPulsePostArchives(
    pulseRows.map((m) => m.pulseSourcePostId || m.id.replace(/^pulse-mem-/, '')).filter(Boolean),
  )
  await Promise.all(pulseRows.map((m) => personaDb.deleteCharacterMemory(m.id)))
}
