import type { ApiConfig } from '../../phone/apps/api/types'
import { personaDb } from '../../phone/apps/wechat/newFriendsPersona/idb'
import type { CharacterMemory } from '../../phone/apps/wechat/newFriendsPersona/types'
import { composeMemoryWithSourcePrefix } from '../../phone/apps/wechat/memory/memorySourceBadges'

import type { MomentItemModel } from './mockMoments'
import {
  buildMomentMemoryBodyText,
  buildUserMomentMentionMemoryContent,
  mergeInteractorMomentMemoryKeywords,
  momentMemoryIdForMomentInteractor,
  summarizeMentionedCharacterMomentResponse,
} from './momentMemoryContentBuilder'
import { extractMomentMemoryKeywords } from './momentMemoryKeywordAi'
import { enrichMomentAttachedMusic } from './momentAttachedMusic'
import { getUserMomentMentionedContacts } from './momentMentionUtils'
import type { MomentsContactDirectory } from './momentsContactDirectory'
import { formatMomentLocationDisplay } from './momentLocationUtils'

const ARCHIVE_DEBOUNCE_MS = 5000

export type UserMomentMentionArchiveJob = {
  moment: MomentItemModel
  apiConfig: ApiConfig | null | undefined
  wechatAccountId: string | null | undefined
  playerIdentityId: string
  playerDisplayName: string
  contactDirectory: MomentsContactDirectory
  now?: number
}

type PendingArchive = {
  timer: number
  job: UserMomentMentionArchiveJob
}

const pendingArchives = new Map<string, PendingArchive>()

async function findMentionMomentMemory(
  interactorCharacterId: string,
  momentId: string,
): Promise<CharacterMemory | null> {
  const list = await personaDb.listCharacterMemoriesForCharacter(interactorCharacterId)
  const stableId = momentMemoryIdForMomentInteractor(momentId, interactorCharacterId)
  return (
    list.find(
      (m) =>
        m.id === stableId ||
        (m.momentSourceMomentId === momentId && m.momentMemoryRole === 'interactor'),
    ) ?? null
  )
}

async function flushUserMomentMentionArchive(job: UserMomentMentionArchiveJob): Promise<void> {
  let moment = job.moment
  if (!moment.isUserAuthored) return

  if (moment.attachedMusic) {
    const enrichedMusic = await enrichMomentAttachedMusic(moment.attachedMusic)
    moment = { ...moment, attachedMusic: enrichedMusic }
  }

  const mentioned = getUserMomentMentionedContacts(moment)
  if (!mentioned.length) return

  const interactionNow = job.now ?? Date.now()
  const archivedAt = Date.now()
  const playerDisplayName = job.playerDisplayName.trim() || '用户'
  const originalText = buildMomentMemoryBodyText(moment) || '（图片动态）'
  const locationLabel = formatMomentLocationDisplay(moment.location)

  const keywords = await extractMomentMemoryKeywords({
    apiConfig: job.apiConfig,
    momentText: originalText,
    location: locationLabel ?? '',
  })

  await Promise.all(
    mentioned.map(async (contact) => {
      const interactorCharId = contact.characterId!.trim()
      const ownSummary = summarizeMentionedCharacterMomentResponse(
        moment,
        interactorCharId,
        interactionNow,
      )
      const interactorBody = buildUserMomentMentionMemoryContent({
        moment,
        playerDisplayName,
        interactorCharId,
        now: interactionNow,
      })
      const interactorKeywords = mergeInteractorMomentMemoryKeywords(
        keywords,
        playerDisplayName,
        ownSummary,
      )
      const existing = await findMentionMomentMemory(interactorCharId, moment.id)
      const createdAt = existing?.createdAt ?? moment.timestamp
      const memoryId = existing?.id ?? momentMemoryIdForMomentInteractor(moment.id, interactorCharId)
      const publishedAt =
        Number.isFinite(moment.timestamp) && moment.timestamp > 0 ? moment.timestamp : createdAt

      const row: CharacterMemory = {
        id: memoryId,
        characterId: interactorCharId,
        content: composeMemoryWithSourcePrefix({ hasMomentTag: true }, interactorBody).slice(0, 4000),
        createdAt,
        updatedAt: archivedAt,
        isAutoGenerated: true,
        memoryScope: 'moment',
        memoryTriggerMode: 'keyword',
        memoryKeywords: interactorKeywords.length ? interactorKeywords : undefined,
        momentSourceMomentId: moment.id,
        momentMemoryRole: 'interactor',
        momentPublisherCharacterId: undefined,
        momentPayload: {
          originalText,
          publishedAt,
          imagesCount: moment.images?.length ?? 0,
          interactionsSnapshot: ownSummary,
          publisherDisplayName: playerDisplayName,
          ownInteractionSummary: ownSummary,
          ...(locationLabel ? { location: locationLabel } : {}),
        },
        ...(job.wechatAccountId?.trim()
          ? { sourceWechatAccountId: job.wechatAccountId.trim() }
          : {}),
        ...(job.playerIdentityId.trim() && job.playerIdentityId !== '__none__'
          ? { sourceSessionPlayerIdentityId: job.playerIdentityId.trim() }
          : {}),
      }

      await personaDb.upsertCharacterMemory(row)
    }),
  )
}

/** 防抖刻录：用户 @ 的角色侧写记忆，供私聊/后续场景召回。 */
export function scheduleUserMomentMentionArchive(job: UserMomentMentionArchiveJob): void {
  if (!job.moment.isUserAuthored) return
  if (!getUserMomentMentionedContacts(job.moment).length) return

  const key = job.moment.id
  const prev = pendingArchives.get(key)
  if (prev) window.clearTimeout(prev.timer)

  const merged: UserMomentMentionArchiveJob = prev
    ? {
        ...prev.job,
        ...job,
        moment: job.moment,
        now: job.now ?? Date.now(),
      }
    : { ...job, now: job.now ?? Date.now() }

  const timer = window.setTimeout(() => {
    pendingArchives.delete(key)
    void flushUserMomentMentionArchive(merged).catch(() => {
      /* 后台任务：静默失败 */
    })
  }, ARCHIVE_DEBOUNCE_MS)

  pendingArchives.set(key, { timer, job: merged })
}

export function cancelUserMomentMentionArchive(momentId: string): void {
  const prev = pendingArchives.get(momentId)
  if (prev) window.clearTimeout(prev.timer)
  pendingArchives.delete(momentId)
}
