import { personaDb } from '../newFriendsPersona/idb'
import type { CharacterMemory } from '../newFriendsPersona/types'
import {
  formatOnlineMemorySummaryStorageBody,
  resolveMemorySummaryRowKeywordsFromParsed,
} from '../memory/onlineMemorySummaryFormat'
import { repairMemorySummaryBodyFromModel } from '../memory/memorySummarySchemaLeakRepair'
import { normalizeStoryTimelineRowTitle } from '../memory/storyTimelineTypes'
import type { DiaryEntry, DiaryMemorySummary } from './diaryTypes'

/** 将日记摘要表反向刻录为角色长期记忆（不入库日记原文） */
export async function archiveDiaryEntryToMemory(params: {
  characterId: string
  entry: DiaryEntry
  memorySummary: DiaryMemorySummary
  wechatAccountId: string | null
  sessionPlayerIdentityId: string
}): Promise<void> {
  const cid = params.characterId.trim()
  if (!cid) return

  const summaryBody = repairMemorySummaryBodyFromModel(params.memorySummary.content).trim()
  if (!summaryBody) return

  const rowTitle =
    normalizeStoryTimelineRowTitle(params.memorySummary.rowTitle) ||
    normalizeStoryTimelineRowTitle(params.entry.title) ||
    '日记'
  const rowKeywords = resolveMemorySummaryRowKeywordsFromParsed({
    rowKeywords: params.memorySummary.rowKeywords,
    content: summaryBody,
  })

  const tableBody = formatOnlineMemorySummaryStorageBody(summaryBody, {
    rowTitle,
    rowKeywords,
  })
  const content = `[日记] ${tableBody}`

  const now = Date.now()
  const memoryId = `diary_${params.entry.id}`

  const row: CharacterMemory = {
    id: memoryId,
    characterId: cid,
    content,
    createdAt: now,
    updatedAt: now,
    isAutoGenerated: true,
    memoryScope: 'private',
    memoryTriggerMode: 'keyword',
    memoryTriggerCategory: '日记',
    memoryTriggerPrecise: rowTitle.slice(0, 10) || params.entry.title.slice(0, 10),
    memoryTriggerEmotionNeed: ['内心', '私密', '独白'],
    memoryKeywords: [...new Set(['日记', rowTitle, ...rowKeywords].filter((x): x is string => Boolean(x?.trim())))],
    sourceWechatAccountId: params.wechatAccountId?.trim() || undefined,
    sourceSessionPlayerIdentityId: params.sessionPlayerIdentityId?.trim() || undefined,
  }

  await personaDb.upsertCharacterMemory(row)
}

/** 删除日记对应的长期记忆刻录 */
export async function removeDiaryEntryFromMemory(entryId: string): Promise<void> {
  const id = entryId.trim()
  if (!id) return
  await personaDb.deleteCharacterMemory(`diary_${id}`)
}
